Fix "AttributeError: 'NoneType' object has no attribute 'get'"
The 'data' value passed to the Manifest constructor can be None. Using
self.data fixes this due to existing logic.

Change-Id: Ibbe7e6386a0d1aab83e522238dedd393116f1232